## DataSource configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=jasoa
#spring.datasource.password=
#
## Hibernate configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
## Server port configuration
#server.port=8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fotoDB?serverTimeZone=UTC&createDatabaseIfNotExist=TRUE
    username: root
    password: P@55word
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: bishop
#    password: jason
#    url: jdbc:postgresql://localhost/postgres
#    platform: postgres
#    initialization-mode: always
#    continue-on-error: true
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    database: postgresql