
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fotoDB?serverTimeZone=UTC&createDatabaseIfNotExist=TRUE
    username: root
    password: P@55word
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    secret-key: 2bvhQJ7TnyKZseqJVaCBO5rWKnk5m3ax


#    image upload size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
